export const ROOM_FULL = { msg: '当前房间人数已满', success: false }
export const ROOM_PLAYING = { msg: '当前房间正在游戏中，无法加入', success: false }
export const REPEAT_JOIN = { msg: '您已加入，请勿重复加入房间', success: false }
export const PLAYER_TOO_LESS = { msg: '人数不足，无法开始', enable: false }
export const PLAYER_NO_READY = { msg: '还有玩家未准备，无法开始', enable: false }
export const GAME_START = { msg: '进入游戏', enable: true }
export const GAME_READY = { msg: 'ready change', enable: false }
export const JOIN_ROOM_EXIST = { success: false, msg: '房间不存在！' }
export const CREATE_ROOM_EXIST = { msg: '创建失败，房间名已存在，请换一个房间名', success: false }